# Generated by Django 3.0 on 2021-05-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
